// PLACEHOLDER

// using UnityEngine;
// 
// public class FPSDisplay : MonoBehaviour
// {
//     public static FPSDisplay Instance { get; private set; }
//     public KeyCode toggleKey = KeyCode.F9;
//     public bool showFPS = true;
// 
//     private float deltaTime = 0.0f;
// 
//     private void Awake()
//     {
//         if (Instance == null)
//         {
//             Instance = this;
//             DontDestroyOnLoad(gameObject);
//         }
//         else
//         {
//             Destroy(gameObject);
//         }
//     }
// 
//     void Update()
//     {
//         if (Input.GetKeyDown(toggleKey))
//         {
//             showFPS = !showFPS;
//         }
// 
//         deltaTime += (Time.deltaTime - deltaTime) * 0.1f;
//     }
// 
//     void OnGUI()
//     {
//         if (!showFPS) return;
// 
//         int w = Screen.width, h = Screen.height;
// 
//         GUIStyle style = new GUIStyle();
//         Rect rect = new Rect(w - 110, 10, 100, h * 2 / 100); 
//         style.alignment = TextAnchor.UpperRight;
//         style.fontSize = h * 2 / 100;
//         style.normal.textColor = Color.white;
//         float fps = 1.0f / deltaTime;
//         string text = string.Format("{0:0.} fps", fps);
//         GUI.Label(rect, text, style);
//     }
// }
